# -*- mode=> ruby; coding=> utf-8 -*-
module RMXCHANNELS
  
  Config = {

    catalog: { 

      30=> "AMBIENT MUSIC",
      52=> "CHILL",
      62=> "DANCE FLOOR",            
      54=> "EXCELLENCE",             
      59=> "FLOW AND PEARLS",        
      55=> "FRONTERAS",              
      57=> "HITS AND TOPS",          
      71=> "INDIE",                               
      26=> "LATIN SOUND",            
      61=> "LATINO",                 
      56=> "LIGHT EXPERIENCE",       
      51=> "LOUNGE",                 
      23=> "MEDITERRANEO",           
      319=> "MUSICAM COVERS",         
      69=> "MUSICAM PLAY",           
      82=> "MUSICAM RHYTHMIC",       
      31=> "MUSICAM SELECT",         
      140=> "MUSICAM SPA",            
      25=> "NEW LOUNGE",             
      65=> "OLDIES HEART",           
      123=> "POP ROCK LATINO",        
      64=> "RETRO",                  
      66=> "RETRO DANCE FLOOR",      
      67=> "RETRO ROCK",             
      27=> "ROCK SHOES",                          
      28=> "SHANGAY",                
      29=> "SPANISH HEART TUNES",    
      58=> "SPANISH HITS",           
      60=> "SPANISH SOUND",          
      24=> "STANDARD SELECT",        
      33=> "TOP ACTUAL",             
      70=> "TRENDY",                 
      63=> "UNDERGROUND DANCE FLOOR",
      97=> "MUSICAM INTERNACIONAL",  
      4=> "CHILL SOFT",             
      36=> "CLASICO LIBRE",          
      46=> "VIAJES",                 
      50=> "BANDAS SONORAS",	     
      53=> "JAZZ WOLRD",
      68=> "ROMPEOLAS",
      72=> "SPANISH PREMIUM",
      81=> "INDIE SOFT",
      84=> "BOSSA NOVA",
      85=> "DIVAS & CROONERS",
      86=> "REGGAE",	 
      92=> "MUSICAM KIDS",
      100=> "HIPSTER PARTY",
      10=> "RHYTHM & BLUES",	
      125=> "POP SUAVE",
      12=> "MUSICAM INFANTIL", 
      13=> "MEXICO TRADICIONAL",
      138=> "AFRICAN RHYTHMS",	  
      185=> "COUNTRY",	
      18=> "Efectos naturaleza",
      273=> "CHILL INSTRUMENTAL",
      304=> "HIT ESPAÑOL",
      305=> "HIT INGLES",
      306=> "TOP ACTUAL INGLÉS",
      32=> "TOP COLOMBIA",
      90=> "Gallego",
      39=> "TOP MEXICO",
      40=> "POP CATALAN",  
      301=> "TOP ACTUAL ESPAÑOL",
    },

    soundreef: {

      91=> "SOUNDREEF LOUNGE-JAZZ",	    
      89=> "SOUNDREEF POP/LOUNGE",	    
      93=> "SOUNDREEF MIXED POP-ROCK",	    
      94=> "SOUNDREEF SOFT POP-ROCK",	    
      95=> "SOUNDREEF LOUNGE/CHILOUT",	    
      96=> "SOUNDREEF ENERGETIC POP-ROCK",	 
      98=> "SOUNDREEF CLUB HOUSE & DANCE",	 
      99=> "SOUNDREEF RNB-BLACK",	    
      108=> "SOUNDREEF LATIN & WORLD",      
      160=> "SOUNDREEF FITNESS & WORKOUT",	 
      161=> "SOUNDREEF BREAKFAST & BRUNCH", 
      131=> "SOUNDREEF INSTRUMENTAL",	    
      32=> "SOUNDREEF POP",                 
    },

    personalized: {

      2=> "PARADORES CIVIA CAFETERIA",      
      3=> "JUGUETRON (BASHA)",                             
      5=> "NESSPRESO",                      
      9=> "PARADORES SPA",                       
      11=> "PARADORES ESENTIA CAFETERIA",     
      17=> "PARADORES NATURIA CAFETERIA",     
      22=> "MUSICAM 257",                                  
      34=> "MERCADONA",                     
      35=> "BOTTICELLI",                                 
      38=> "SIMORRA",                                        
      41=> "OYSHO",                             
      43=> "ORANGE",                              
      44=> "ORANGE MAÑANAS",                      
      45=> "ORANGE TARDE/FINES DE SEMANA",                 
      48=> "BASHA ELECTROPOP",              
      49=> "MUSICAM 256",                                  
      76=> "DOUGLAS",                             
      77=> "CLAIRE S",                      
      78=> "CARREFOUR",                     
      79=> "SPRINGFIELD",                                  
      80=> "CORTEFIEL/PDH",                                
      83=> "FIFTY FACTORY",                                  
      87=> "DEMO CLAIRE S",                     
      88=> "DEMO WOMEN SECRET",                        
      90=> " AHORRAMAS",
      101=> "PARADORES ESENTIA",              
      102=> "PARADORES NATURIA",              
      103=> "PARADORES CIVIA",                      
      104=> "PARADORES AIGUABLAVA POP",     
      105=> "CORTEFIEL DEMO",                     
      106=> "PARADORES AIGUABLAVA CHILL",                
      120=> "PARADORES ESENTIA 2",              
      121=> "PARADORES NATURIA 2",
      307=> "Nh Hotels",                                  
      308=> "Nh Collection Contemporary Style",         
      309=> "Nh Collection Boutique",                         
      311=> "Nh Hotels Collection Contemporary Style Alemania",
      312=> "Nh Hotels España",                         
      314=> "Nh Hotels Collection Boutique España",          
      805=> "CUSTO DEMO", 
      1857=>"ORANGE POR LAS TARDES", 
      1856=>"ORANGE POR LAS MAÑANAS"                             
    }
 }    
end